//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.SC = new HashSet<SC>();
        }
    
        public int CID { get; set; }
        public string CName { get; set; }
        public Nullable<int> TID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<SC> SC { get; set; }
    }
}
