//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.SC = new HashSet<SC>();
        }
    
        public int SID { get; set; }
        public string SName { get; set; }
        public Nullable<int> SAge { get; set; }
        public Nullable<int> SSex { get; set; }
    
        public virtual ICollection<SC> SC { get; set; }
    }
}
